### ISSUE TITLE
Autoload breakpoint of init_templates means language strings using ez pages cannot use Ceon

### ISSUE THREAD

**Issue by neekfenwick** [JSWebSteve/Ceon-URI-Mapping-V5.1.0#5]
Wondering if anyone else has run into this.  I tried altering our `tpl_footer.php` string `FOOTER_TEXT_BODY` like this:

```
    'FOOTER_TEXT_BODY' => 'Copyright &copy; ' . date('Y') .
        '&nbsp;<a href="' . zen_ez_pages_link(4, 0, 'SSL', true) . '" target="_blank">Mickey Mouse Inc</a> All rights reserved.',

```

Unfortunately this code is executed during breakpoint 110 when `init_templates.php` runs the line `$languageLoader->loadInitialLanguageDefines();`.  At this point, the Ceon class CeonUriMappingLinkBuild has not registered as an Observer of `NOTIFY_SEFU_INTERCEPT` and so the `zen_href_link` call doesn't translate the URL for the EZ Page to the SEO Friendly version in the language string.

`config.ceon_uri_mapping.php`:
```
$autoLoadConfig[165][] = array(
    'autoType' => 'classInstantiate',
    'className' => 'CeonUriMappingLinkBuild',
    'objectName' => 'ceon_uri_mapping_link_build'
     );
```

Changing the breakpoint `165` to a value lower than `110` e.g. `100` fixes the problem.  My question is, what sensible value should it be set to?

**Comment by JSWebSteve** [comment]
Changes merged. Thank you for highlighting this issue and providing a fix.
